INSERT INTO `ims`.`customers` (`first_name`, `surname`) VALUES ('jordan', 'harrison');
INSERT INTO `ims`.`customers` (`first_name`, `surname`) VALUES ('chris', 'perrins');
INSERT INTO `ims`.`customers` (`first_name`, `surname`) VALUES ('piers', 'barber');
INSERT INTO `ims`.`items` (`item_name`, `item_price`, `item_quantity`) VALUES ('harmonica', 1200.99, 8);
INSERT INTO `ims`.`items` (`item_name`, `item_price`, `item_quantity`) VALUES ('wheelie bin', 2.99, 84528);
INSERT INTO `ims`.`items` (`item_name`, `item_price`, `item_quantity`) VALUES ('your mother', 0.99, 1);
INSERT INTO `ims`.`items` (`item_name`, `item_price`, `item_quantity`) VALUES ('nike airs', 40.99, 74);
INSERT INTO `ims`.`orders` (`fk_customer_id`) VALUES (3);
INSERT INTO `ims`.`orders` (`fk_customer_id`) VALUES (1);
INSERT INTO `ims`.`orders_items` (`fk_order_id`,`fk_item_id`) VALUES (1,4);
INSERT INTO `ims`.`orders_items` (`fk_order_id`,`fk_item_id`) VALUES (1,1);
INSERT INTO `ims`.`orders_items` (`fk_order_id`,`fk_item_id`) VALUES (1,2);
INSERT INTO `ims`.`orders_items` (`fk_order_id`,`fk_item_id`) VALUES (2,2);
INSERT INTO `ims`.`orders_items` (`fk_order_id`,`fk_item_id`) VALUES (2,2);
INSERT INTO `ims`.`orders_items` (`fk_order_id`,`fk_item_id`) VALUES (2,2);
INSERT INTO `ims`.`orders_items` (`fk_order_id`,`fk_item_id`) VALUES (2,2);
INSERT INTO `ims`.`orders_items` (`fk_order_id`,`fk_item_id`) VALUES (2,2);
INSERT INTO `ims`.`orders_items` (`fk_order_id`,`fk_item_id`) VALUES (2,2);
INSERT INTO `ims`.`orders_items` (`fk_order_id`,`fk_item_id`) VALUES (2,2);
INSERT INTO `ims`.`orders_items` (`fk_order_id`,`fk_item_id`) VALUES (2,2);
INSERT INTO `ims`.`orders_items` (`fk_order_id`,`fk_item_id`) VALUES (2,2);
INSERT INTO `ims`.`orders_items` (`fk_order_id`,`fk_item_id`) VALUES (2,2);

